AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  unify-posts-sam

  SAM Application for unify-posts-sam

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 120

    # You can add LoggingConfig parameters such as the Logformat, Log Group, and SystemLogLevel or ApplicationLogLevel. Learn more here https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-loggingconfig.
    LoggingConfig:
      LogFormat: JSON
Resources:
  YouTubeUploaderFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/youtube-upload.handler
      Runtime: nodejs22.x
      MemorySize: 1024
      CodeUri: upload-function
      Policies:
        - AWSLambdaBasicExecutionRole
      Environment:
        Variables: {}
        # All credentials are now provided dynamically in the request body.
      Events:
        UploadVideo:
          Type: Api
          Properties:
            Path: /youtube/upload-video
            Method: POST

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: 'true'
Outputs:
  YouTubeUploaderApi:
    Description: 'API Gateway URL for YouTube Video Uploader'
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/upload/'
  YouTubeUploaderFunctionArn:
    Description: 'YouTube Uploader Lambda Function ARN'
    Value: !GetAtt YouTubeUploaderFunction.Arn
  YouTubeUploaderFunctionIamRole:
    Description: 'IAM Role for YouTube Uploader Function'
    Value: !GetAtt YouTubeUploaderFunctionRole.Arn
